title: Jay Smith
logo: "/images/progilr.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  InfoSec Carnival Barker 
  <br><br>
  Volatility is my jam
  <br><br>
  <a href="https://www.linkedin.com/in/jaysmith502/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal

